services:
  aqc:
    image: evaluation/aqc
    container_name: aqc
    volumes:
      - ../data:/app/data
      - ../models:/app/models
    ports:
      - "1111:1111"
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py